### ISSUE TITLE
edf.plot does not work on its own

### ISSUE THREAD

**Issue by silberzwiebel** [jashubbard/edfR_test#2]
Hi there,
thanks for this package!

I think I found a bug, but maybe I just missed something.

I wanted to use `edf.plot`without loading an edf-file before and used this command:

```
> edf.plot('s10.edf')
Reading Events from s10.edf ...Success! (43643 events)
Fehler in basename(f) : Objekt 'f' nicht gefunden
```

I do not see a plot. The error translates to `error in basename(f): Object 'f' not found`
If I load the edf file like the following I see a plot:

```

> e = edf.events('s10.edf')
Reading Events from s10.edf ...Success! (43643 events)
> edf.plot(NULL, e)
```

**Comment by jashubbard** [comment]
Good catch. Just a small typo in the code. It should be working now. 
Thanks!

**Comment by silberzwiebel** [comment]
Works fine now, thank you!
