### ISSUE TITLE
Tagging non-standard events (logged in messages)

### ISSUE THREAD

**Issue by fusaroli** [jashubbard/edfR_test#5]
Thanks for the great package! I am using it to extract data from a paradigm in which each trial has a substructure. E.g. Trial n has a fixation cross that appears 118 ms after the beginning of the trial and lasts for a second, a stimulus appears and stays until a button is pressed, etc. These events are logged in the messages (e.g. 724080 fixation_start), so they can be extracted and used to tag the other extracted data (e.g. samples or fixations). I am writing my own parsing script to do that, but I was wondering whether there's an already coded alternative within the package, which I have overlooked.

**Comment by tmalsburg** [comment]
To my knowledge there is no support for marking events based on information contained in messages.  However, it is relatively easy to do this yourself.  You can get the messages with this code:

``` R
trials <- edf.trials(fname)
m <- trials$messages
```

Then you extract the start and end points of the time intervals that you want to mark from the messages.  Once you have them, you can use the functions from the intervals package to mark events.  Basically, you define time intervals and then use the `intervals_overlap` to test which in a vector of event time stamps are in these intervals.  Hope that helps.

**Comment by jashubbard** [comment]
Not if it will do _exactly_ what you want out of the box, but I have another package, itrackR (http://github.com/jashubbard/itrackR) that is designed to handle more high-level aspects of the analysis. You could use it to create epochs of your fixation (or saccade) data, relative to the start of the fixation (or any other message you send to Eyelink).

**Comment by fusaroli** [comment]
Thanks both for the comments. I have now a script parsing the messages for arbitrarily defined events and tagging the corresponding samples/fixations/etc (albeit quite slowly on large datasets). Good to know I haven't done redundant work :-)
