### ISSUE TITLE
Batch import of headref

### ISSUE THREAD

**Issue by fusaroli** [jashubbard/edfR_test#6]
sorry for bothering again, but just a small thing: is there a way to import head references from edf.batch?
That is, "hxL", "hxR", "hyL", "hyR".

I wrote my own loop to do that relying on edf.samples, but using edf.batch would get me much cleaner code.

**Comment by jashubbard** [comment]
Ok, I've added that functionality to edf.batch. You can now specify fields you want using sample.fields and/or event.fields.

**Comment by fusaroli** [comment]
thanks
